### ISSUE TITLE
Annotations in a separate package?

### ISSUE THREAD

**Issue by serj-lotutovici** [serj-lotutovici/moshi-lazy-adapters#19]
Makes sense for clarity. and structure. may be something like `com.serjltt.moshi.adapters.annotations`?

What do you think?
cc @vanniktech

**Comment by vanniktech** [comment]
Hmm I don't think this is necessary plus it's another breaking change that would come with the 1.1 version.

**Comment by serj-lotutovici** [comment]
Definably not for 1.1... I will think over this one, if it makes sense.

**Comment by serj-lotutovici** [comment]
Closing in favour of #39
