### ISSUE TITLE
Retrofit - Unwrapping response when not wrappable yields in Single#NoSuchElementException

### ISSUE THREAD

**Issue by vanniktech** [serj-lotutovici/moshi-lazy-adapters#33]
Imagine the Retrofit Interface with the following method:

```java
@Wrapped("query", "results", "channel") @GET("path") Single<Something> doSomething();
```

If I get a response that can be unwrapped I get my `Single<Something>`, for instance:

```json
{
  "query": {
    "results": {
      "channel": {
          ...
        }
      }
    }
  }
}
```

However if I get something back that can't be:

```json
{
  "query": {
    "results": null
  }
}
```

I end up with a Single that errors NoSuchElementException. My guess is, that our WrappedAdapter does not return the deserialized class which will end up in an Observable that only completes and then [this line](https://github.com/square/retrofit/blob/99c0b85d6cf4e8b80952fa7fc281f546e2de284c/retrofit-adapters/rxjava2/src/main/java/retrofit2/adapter/rxjava2/RxJava2CallAdapter.java#L72) will convert the Observable to Single with NoSuchElementException.

Is this behavior wanted?

**Comment by serj-lotutovici** [comment]
By the looks of it, the Adapter it self, behaves as expected (returns `null` when nothing is found). But may be we need a more graceful behaivure that will yield a `JsonDataException` if the path is not satisfied.

A non breaking solution would be to introduce a `failOnPathNotFound` (or something like that) flag to the `@Wrapped` annotation.

**Comment by vanniktech** [comment]
If it were to return null, would not RxJava 2 would throw earlier than the `singleOrError` operator? I think it's just not emitting anything.

**Comment by serj-lotutovici** [comment]
Checked the source code. We actually throw an `IOException`, instead of a `JsonDataException`, so no nulls there. Will investigate, and comeback to you asap.

**Comment by vanniktech** [comment]
How does the IoException then get swallowed?

**Comment by serj-lotutovici** [comment]
by design no...
