### ISSUE TITLE
Version 2 consider making failOnDefault by default true in @Wrapped

### ISSUE THREAD

**Issue by vanniktech** [serj-lotutovici/moshi-lazy-adapters#37]
How do you feel making failOnDefault by default true in @Wrapped as part of a breaking change for 2.0?

**Comment by serj-lotutovici** [comment]
I would also rename `@Wrapped.value()` to `@Wrapped.path()`.

**Comment by vanniktech** [comment]
Sounds legit

**Comment by serj-lotutovici** [comment]
Tracking via #39
