### ISSUE TITLE
Version 2.0 Planing

### ISSUE THREAD

**Issue by serj-lotutovici** [serj-lotutovici/moshi-lazy-adapters#39]
Placeholder issue, for discussions regarding changes in 2.0.

**Api changes:**
- [x] `@Wrapped` make `failOnNotFound default true`.
- [x] `@Wrapped` rename `value()` to `path()`
- [x] Make all adapters package protected and expose the factory via a static field (ex. `ADAPTER_FACTORY`).

**Comment by vanniktech** [comment]
What about #19? This can also be done for 2.0

**Comment by serj-lotutovici** [comment]
#19 conflicts with making adapters package private. In general I was thinking about a simple api, that would show a direct correlation between the annotation and the adapter.
Currently we have the following:
```java
@interface @SomeAnnotation {
}
```
and
```java
class SomeAnnotationJsonAdapter {
}
```
This means that we always have to maintain a 1to1 naming convention for all adapters. But that brakes in the case when an adapter can handle multiple annotation (ex. `@FirstElement` and `@ElementAt`).

The simple way would be to move all factory instances under the respective annotations. 

In any case the goal should be to keep things simple, since this library serves the purpose of providing extension for moshi, and nothing more.

**Comment by serj-lotutovici** [comment]
I would also sync the 2.0.0 release with moshi's 1.4.0 which will bring some improvements, and will also expose some api's, that can help make these adapters as efficient as the internal ones in moshi.
