### ISSUE TITLE
Can it process an ordered adapter on response type?

### ISSUE THREAD

**Issue by muhrifqii** [serj-lotutovici/moshi-lazy-adapters#42]
For instance, when my json looks like:
```
{
   "data" : [
      {
         "book_id" : "doe",
         "author_data" : [
            {
               "name" : "John Doe",
               "id" : "john_doe"
            }
         ],
         "title" : "Doe The John Doe",
      }
   ],
   "index_searched" : "book_id"
}
```
Could it be annotated like this?
```
@GET("/book/{key}")
  @Wrapped("data") @FirstElement fun aBook(@Path("key") key: String): Observable<Book>
```

**Comment by serj-lotutovici** [comment]
Yes. Checkout [this test class](https://github.com/serj-lotutovici/moshi-lazy-adapters/blob/master/src/integrationTest/java/com/serjltt/moshi/adapters/LazyAdaptersRetrofitTest.java) as an example.

**Comment by muhrifqii** [comment]
@serj-lotutovici Thank you. I think it would be better if such combination or concurrent annotation is mentioned on readme
