### ISSUE TITLE
Proposal: Transient

### ISSUE THREAD

**Issue by hzsweers** [serj-lotutovici/moshi-lazy-adapters#43]
There's serializeonly and deserializeonly (which is the most similar), but maybe for semantics and clarity it would be useful to have a transient one that just exludes a field from any serialization.

**Comment by serj-lotutovici** [comment]
Makes sense. I assume you want this for auto-value-moshi.

**Comment by vanniktech** [comment]
That annotation should have only method as a target since Moshi supports `transient` on member variables out of the box.
