### ISSUE TITLE
Allow parameterized types in DefaultOnDataMismatchAdapter

### ISSUE THREAD

**Issue by veyndan** [serj-lotutovici/moshi-lazy-adapters#55]
I have a use case where a data mismatch occurs for `A<B>`. With the current implementation of `DefaultOnDataMismatchAdapter#newFactory` this isn't possible to parse as the first parameter of the method is `Class<T> type`. Ideally this method would accept `Type` instead of `Class<T>` and then my usage would be:
```
Type type = Types.newParameterizedType(A.class, B.class);
A<B> defaultValue = new A<>(new B());
DefaultOnDataMismatchAdapter.newFactory(type, defaultValue);
```

**Comment by serj-lotutovici** [comment]
First of all, thank you for the feedback. Secondly, sorry for the delayed reply, I've been jammed for a while.

Thirdly, that's a little bit trickier then it looks. Moshi has a private api `Types.equals(Type, Type)` that could help us out. I'll see if the authors agree to make it public, if not we'll just fork the functionality.

**Comment by veyndan** [comment]
No worries, and thanks for getting back to me. Awesome, I'd have a look myself but I'm a bit swamped for the next few weeks. Thanks for the wonderful library!
