### ISSUE TITLE
FallbackInt crashes on Turkish 

### ISSUE THREAD

**Issue by yayaa** [serj-lotutovici/moshi-lazy-adapters#65]
[This code](https://github.com/serj-lotutovici/moshi-lazy-adapters/blob/master/src/main/java/com/serjltt/moshi/adapters/FallbackOnNull.java#L107) will generate `fallbackİnt` instead of `fallbackInt` since we have a capital `i` in Turkish  :) and that will throw an exception

**Comment by vanniktech** [comment]
Fixed by #66

Thanks

**Comment by vanniktech** [comment]
I thought they had. I don't think this project is using error prone though.

**Comment by NightlyNexus** [comment]
EP doesn't have one yet. https://github.com/google/error-prone/issues/632
